### ISSUE TITLE
现在实现的和直接传到一个目录 nginx访问 有啥优势么?

### ISSUE THREAD

**Issue by weichangdong** [lantongxue/young-pictures#2]
大概看了下 php代码 本地存储的show基本是靠file_get_contents实现的 第一个问题 如题
第二个问题就是 
这个算cdn么,因为对图片cdn的原理 不了解

**Comment by lantongxue** [comment]
第一个问题：主要原因在于存储引擎组件的实现，这里只是契合了这个组件，所以对文件的读写都是靠这个组件去实现的。如果要和直接放到web目录访问对比的话也没有太多优势，第一个优势：可控性，这个就不多说了。第二个优势：解耦，由一个组件去管理各种云商或者其他存储方案。比如：A图片放到本地，B图片在云存储上面，这个时候优势就体现出来了。直链访问是很简单直接，但是我要对图片做访问计次，所以会有中间这一层。

第二个问题：这个不算CDN，CDN是内容分发。。。

**Comment by weichangdong** [comment]
奥 谢谢解答
如果本地存储的话 现在没法分布式吧

**Comment by lantongxue** [comment]
> 奥 谢谢解答
> 如果本地存储的话 现在没法分布式吧

是的，现在分布式只能用云存储。
